import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import React from "react";
import ActiveSectionContextProvider from "@/context/active-section-context";
import { Analytics } from "@vercel/analytics/react";
import Footer from "@/components/footer";
import DarkModeToggle from "@/components/darkmodetoggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ishika Agarwal",
  description: "Generated by Ishika Agarwal",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body
        className={`
    ${inter.className} 
    text-black dark:text-white
    bg-gradient-to-br from-teal-50 to-rose-50
    dark:bg-gradient-to-b dark:from-[#0f0f0f] dark:via-[#111827] dark:to-[#1f2937]
    transition-colors duration-500
  `}
      >
        <ActiveSectionContextProvider>
          <Header />
          {children}
          <Footer />
        </ActiveSectionContextProvider>

        <DarkModeToggle />
        <Analytics />
      </body>
    </html>
  );
}
